before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

script:
  - mvn clean install
  - mvn heroku:deploy -X jib:build -P deploy-heroku,deploy-docker
