before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:11-jre-slim-sid

script:
  - echo "$JAVA_OPTS"
  - mvn clean install
  - mvn heroku:deploy jib:build -P deploy-heroku,deploy-docker
